language: java
sudo: required
jdk:
#  - oraclejdk9
  - oraclejdk8
  - oraclejdk7
#  - oraclejdk6 - End of life
#  - openjdk8 - Unknown
#  - openjdk7
#  - openjdk6

# enable codecov reporting...
after_success:
  - bash <(curl -s https://codecov.io/bash)


# disable email notifications...
notifications:
  email: false


# enable gradle dependency caching...
before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
